### ISSUE TITLE
There should be a group e-mail

### ISSUE THREAD

**Issue by bjorgve** [uit-no/research-software.uit.no#14]
We should have a RSE email, such that all correspondence rely on a single member.

**Comment by bast** [comment]
Full agreement. But where should the email go to? To a ticketing system? TopDesk? Or simply an alias that forwards to a bunch of emails?

**Comment by bjorgve** [comment]
I think an alias that forwards to a bunch of emails is best to begin with. We can go for a ticketing system when that solution is no longer sustainable.

**Comment by Danzelot** [comment]
We now have topdesk and an email (rse@uit.no) forwarding to it.

Closed by #18 .
